config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :clients
  resources :events
  resources :sellers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_many :events
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :cars
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :seller
  belongs_to :car
  has_many_attached :images
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:plate, :description, :client_id)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :email)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      puts params
      params.require(:event).permit(:name, :price, :description, :seller_id, :date, :car_id, images: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: %i[ show edit update destroy ]

  # GET /sellers or /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1 or /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers or /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully created." }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1 or /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully updated." }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1 or /sellers/1.json
  def destroy
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url, notice: "Seller was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seller_params
      params.require(:seller).permit(:name, :charge, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Placa:</strong>
    <%= car.plate %>
  </p>

  <p>
    <strong>Descripción del carro:</strong>
    <%= car.description %>
  </p>

  <p>
    <strong>Cliente:</strong>
    <%= Client.find(car.client_id).name %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibió este carro de ser guardado:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Placa", style: "display: block" %>
    <%= form.text_field :plate, required: true%>
  </div>

  <div>
    <%= form.label "Descripción", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label "Cliente", style: "display: block" %>
    <%= form.collection_select :client_id, Client.all, :id, :name, required: true %>
  </div>

  <br>
  
  <div>
    <% if edit %>
      <%= form.submit "Editar carro" %>
    <% else %>
      <%= form.submit "Crear carro" %>
    <% end %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editar carro</h1>

<%= render "form", car: @car, edit: true %>

<br>

<div>
  <%= link_to "Devuelta al inicio", root_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carros</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Mostrar", car %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo carro", new_car_path %>
<%= link_to "Regresar al inicio", root_path %>

app/views/cars/new.html.erb
<h1>Nuevo Carro</h1>

<%= render "form", car: @car, edit: false %>

<br>

<div>
  <%= link_to "Devuelta al inicio", root_path %>
</div>

<div>
  <%= link_to "Ir a carros", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Editar carro", edit_car_path(@car) %> |
  <%= link_to "Devuelta a los carros", cars_path %>

  <%= button_to "Destruir este carro", @car, method: :delete %>
</div>

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nombre:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Nombre", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label "Email", style: "display: block" %>
    <%= form.text_field :email, required: true %>
  </div>

  <div>
    <%= form.submit "Crear cliente" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Mostrar", client %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo cliente", new_client_path %>
<%= link_to "Regresar al inicio", root_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Devuelta al inicio", root_path %>
</div>

<div>
  <%= link_to "Ir a clientes", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Seller:</strong>
    <%= event.seller_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <% if event.images.present? %>
      <% event.images.each do |image| %>
        <%= image_tag image %>
      <% end %>
    <% else %>
      <p>No tiene imagenes adjuntas</p>
    <% end %>
  </p>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Nombre", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label "Precio", style: "display: block" %>
    <%= form.text_field :price, required: true %>
  </div>

  <div>
    <%= form.label "Descripción", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label "Vendedor", style: "display: block" %>
    <%= form.collection_select :seller_id, Seller.all, :id, :name, required: true %>
  </div>

  <div>
    <%= form.label "Carro", style: "display: block" %>
    <%= form.collection_select :car_id, Car.all, :id, :plate, required: true %>
  </div>

  <div>
    <%= form.label "Fecha", style: "display: block" %>
    <%= form.date_field :date, required: true %>
  </div>

  <div>
    <%= form.label "Imagenes" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit "Crear evento" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Devuelta al inicio", root_path %>
</div>

<div>
  <%= link_to "Devuelta a eventos", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/home/index.html.erb
<div>
  <h1> Almacén Susllantas </h1>
  <div>
    <p>Crear evento de Carro</p>
    <%= button_to "Crear evento", new_event_path, method: :get %>
    <p>Crear carro</p>
    <%= button_to "Crear carro", new_car_path, method: :get %>
    <p>Crear cliente</p>
    <%= button_to "Crear cliente", new_client_path, method: :get %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Susllantas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sellers/_form.html.erb
<%= form_with(model: seller) do |form| %>
  <% if seller.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
        <% seller.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :charge, style: "display: block" %>
    <%= form.text_field :charge %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sellers/_seller.html.erb
<div id="<%= dom_id seller %>">
  <p>
    <strong>Name:</strong>
    <%= seller.name %>
  </p>

  <p>
    <strong>Charge:</strong>
    <%= seller.charge %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= seller.email %>
  </p>

</div>

app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render "form", seller: @seller %>

<br>

<div>
  <%= link_to "Show this seller", @seller %> |
  <%= link_to "Back to sellers", sellers_path %>
</div>

app/views/sellers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sellers</h1>

<div id="sellers">
  <% @sellers.each do |seller| %>
    <%= render seller %>
    <p>
      <%= link_to "Show this seller", seller %>
    </p>
  <% end %>
</div>

<%= link_to "New seller", new_seller_path %>

app/views/sellers/new.html.erb
<h1>New seller</h1>

<%= render "form", seller: @seller %>

<br>

<div>
  <%= link_to "Back to sellers", sellers_path %>
</div>

app/views/sellers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @seller %>

<div>
  <%= link_to "Edit this seller", edit_seller_path(@seller) %> |
  <%= link_to "Back to sellers", sellers_path %>

  <%= button_to "Destroy this seller", @seller, method: :delete %>
</div>